# Generated by Django 3.0 on 2021-04-02 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ground',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='shift',
            field=models.CharField(default=datetime.datetime(2021, 4, 2, 10, 36, 42, 756430, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
