# Generated by Django 3.0 on 2021-04-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Feedback',
        ),
    ]
