# Generated by Django 3.0 on 2021-04-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20210405_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='fb_name',
        ),
    ]
