# Generated by Django 3.1.7 on 2021-04-08 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20210407_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AddField(
            model_name='ground',
            name='price',
            field=models.CharField(default=datetime.datetime(2021, 4, 8, 10, 32, 25, 883476, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
